version: '3.5'
services:
  postgres:
    image: postgres:13
    environment:
            POSTGRES_PASSWORD: postgres_password

  adminer:
    image: adminer
    restart: always
    ports:
      - 5434:5432

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DB: nest
